dist: trusty
sudo: required
language: bash
env:
  - ansible_version=2.7.1 ansible_lint_version=3.5.1 tf_version=0.11.10 tf_lint_version=0.7.2
before_install:
#- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
#  bash 
install:
  # install ansible
  - sudo pip install --upgrade pip
  - sudo pip install ansible==${ansible_version} ansible-lint==${ansible_lint_version}
  # install terraform & tf-lint
  - mkdir tools
  - wget https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip
  - unzip -u terraform_${tf_version}_linux_amd64.zip 
  - wget https://github.com/wata727/tflint/releases/download/v${tf_lint_version}/tflint_linux_amd64.zip
  - unzip -u tflint_linux_amd64.zip -d tools/
  # variables
  - cp packer/variables.json.example packer/variables_immutable.json
  - mv packer/variables.json.example packer/variables.json
  # set env
  - export PATH="$PATH:`pwd`/tools"
script:
  # validate packer
  - packer validate -var-file=packer/variables.json packer/app.json
  - packer validate -var-file=packer/variables.json packer/db.json
  - cd packer
  - packer validate -var-file=variables.json ubuntu16.json
  - packer validate -var-file=variables_immutable.json immutable.json
  - cd -
  # validate terraform
  - cd terraform/stage
  - terraform init -backend=false && terraform validate && tflint
  - cd -
  - cd terraform/prod
  - terraform init -backend=false && terraform validate && tflint
  - cd -
  - cd ansible
  - ansible-lint playbooks/site.yml --exclude=roles/jdauphant.nginx
# comment
notifications:
  slack:
    rooms:
      secure: SbKuh5Cm847c7lFkD9dzQXL1YXs05dEh/Pjf8dKxGwC7fzDIMlkrzEN5ZC5nBJhvZsyrgl0I9weVoLeQQsVJruZkHN9nogNB2+gbd20uw75pDHKNQKCf3vAXydl2PbrLAh4oURCgNZ1KfuVMH05v17nWdHEAVAGRJcR9OPUxgLbai8GD1xmev506Yx8B6ftUUtvV5Gamej6Wjl/G3HIL6DXdbM9NHbXZdtQ9dEOni5xMU1eveUvdJme+nA0CsPE9np3P4l79mX8H1yqyeAiV/UnBAEZg6KcxUGESR7Tc3/bCT4eElyqmWDHtXFqBIxtC3+CCTIy8cRTelLsB5u1ngL2iqN2EsO1SGnxJc0JGKR+bZ1YGd1XHhlh3K+8LEHyNSDSik1xVEQX7R8FU+/XSUQp8Bg1uFVMDZoPT/eJVT+gN2OzcI1ffCbKtx3eP8C5Iw6anRn+fiVNvQ9fbWs/2nQdDaxG7UCePmhQsCb9aBvFGNbKGCMruFogfmACEmld61jfJVXd7kzCKTi5SxERJ4Ts8HgyXZ0RaHtEMxadb/d1B6eJ2X419Vjr885btHULHKueePO3ZBuum272jLRJoxoyw7NGJ4E5Xdjjwciey1snCEOAE+QcPrS2XnzpE+nkDitzpFpU9NlqIMDD1RmTIQkJ3oTuZs/QHiKelcLUI/oE=
