---
- name: Install ruby  
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Install ruby
      apt:
        name: ["ruby-full","ruby-bundler","build-essential"]
        state: present
