---
- name: Configure hosts and deploy
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host:       0.0.0.0
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: copy config
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
    - name: copy systemd unit    
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag  
      notify: reload puma

    - name:  Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      tags:  deploy-tag
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag
      notify: reload puma

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted
    - name: reload puma
      service: name=mongod state=restarted

